name: Build_Kernel_for_OpenHD

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: install dependencies
      run: |
        sudo apt install -y build-essential gcc-aarch64-linux-gnu bison qemu-user-static qemu-system-arm qemu-efi u-boot-tools binfmt-support debootstrap flex libssl-dev bc rsync kmod cpio xz-utils fakeroot 
        sudo apt install -y parted udev dosfstools uuid-runtime git-lfs device-tree-compiler python2 python3 python-is-python3 fdisk bc

    - name: clone drivers into kernel
      run: |
        mkdir workdir
        cd workdir
        git clone https://github.com/OpenHD/rtl8812au -b rockchip
        cd rtl8812au
        mkdir -p ../../drivers/net/wireless/rtl8812au
        mv * ../../drivers/net/wireless/rtl8812au/
        cd ../.. 
        rm -Rf workdir
        cd drivers/net/wireless/
        echo 'obj-$(CONFIG_RTL8812AU) += rtl8812au/' >> Makefile
        sed -i '1s/^/CONFIG_RTL8812AU=m\n/' ../../../arch/arm64/configs/rockchip_linux_defconfig
        echo "debug on"
        echo "$(cat Makefile)"
        echo "debug off"
        echo "debug on config"
        cat ../../../arch/arm64/configs/rockchip_linux_defconfig
        echo "debug off"
        sed -i '52s/.*/source "drivers\/net\/wireless\/rtl8812au\/Kconfig"/' Kconfig
        echo "debug on"
        echo "$(cat Kconfig)"
        echo "debug off"
        cd ../../../


    - name: build kernel
      run: |
        dpkg-buildpackage -a "$(cat debian/arch)" -d -b -nc -uc
        ls -a ../
        cd .. 
        cp *.deb linux-rockchip/
  
    - name: Upload to Github
      uses: 'actions/upload-artifact@v2'
      with:
        name: "rock5-kernel-openhd"
        path: |
          *.deb
          linux-rockchip/*.deb
          
    - name: Push
      id: push
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: "push"
        format: "deb"
        owner: "openhd"
        repo: "openhd-2-3-evo"
        distro: "ubuntu"
        release: "jammy"
        republish: "true" # needed ONLY if version is not changing
        file: "linux-image*.deb"

    - name: Push header
      id: push_headers
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: "push"
        format: "deb"
        owner: "openhd"
        repo: "openhd-2-3-evo"
        distro: "ubuntu"
        release: "jammy"
        republish: "true" # needed ONLY if version is not changing
        file: "linux-header*.deb"

